### ISSUE TITLE
Spacing around active items if using sections, but not tabs

### ISSUE THREAD

**Issue by michalc** [ministryofjustice/mkdocs-tech-docs-template#12]
There seems to be a slightly strange (to my eye) spacing, around the active items in the left hand navigation menu. This can be seen here next to the "Getting started" item, where the vertical blue bar is very close to the text:

![image](https://user-images.githubusercontent.com/13877/221489368-6d9daa36-16f7-4d9a-8ddf-d677d7291026.png)

Adding this CSS seems to sort it:
```css
.md-nav__item--section > .md-nav > .md-nav__list > .md-nav__item--active {
    margin-left:  0;
    padding-left: 3px;
}
```
I've done this at https://github.com/uktrade/stream-zip/blob/e09ac51c3f21938d2d9b18478892d4f8caaac47e/docs/assets/dit-extra.css, where its effect can currently be seen at https://stream-zip.docs.data.trade.gov.uk/getting-started/ and in the below screenshot

![image](https://user-images.githubusercontent.com/13877/221489400-91d0f210-779c-49cd-a05a-9da23812c15f.png)

After a bit of trial and error, I _think_ it's due to using navigation.sections, but _not_ navigation.tabs as features in mkdocs.yml, as is done in https://github.com/uktrade/stream-zip/blob/5cf1edec090f8abb912f05df610bef0aaecae534/mkdocs.yml
